version: '2'
services:
  webapp:
    build: .
    volumes:
      - ./client:/var/app/current/client:ro
    ports:
      - "3000:3000"
    env_file:
      - ./localdev.env
    networks:
      - frontend

  nginx:
    restart: always
    build: ./docker-assets/nginx/
    ports:
      - "8080:8080"
    networks:
      - frontend

networks:
  frontend:
