version: '2'
services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./localdev.env
    networks:
      - frontend

  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:8080"
    networks:
      - frontend

networks:
  frontend:
