version: '2'
services:
  "webapp-digitopia":
    build:
      context: .
      dockerfile: Dockerfile-webapp
    ports:
      - "3000:3000"
    env_file:
      - ./localdev.env
    networks:
      - frontend

  "nginx-digitopia":
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:8080"
    networks:
      - frontend

networks:
  frontend:
